// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRb48_8wzDVjJoR4C8DgQcUyHfFxh32yU',
    appId: '1:875225395768:web:23526ac0638355747daccd',
    messagingSenderId: '875225395768',
    projectId: 'basic-stripe',
    authDomain: 'basic-stripe.firebaseapp.com',
    storageBucket: 'basic-stripe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPli6-r9py9pWLp2zjb7fKTqC8hECNuw',
    appId: '1:875225395768:android:5cb8119aea3afb067daccd',
    messagingSenderId: '875225395768',
    projectId: 'basic-stripe',
    storageBucket: 'basic-stripe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs8COsUTU0cJrw3vyYGp3_QeYlTm2-PaM',
    appId: '1:875225395768:ios:22442f9968c297fa7daccd',
    messagingSenderId: '875225395768',
    projectId: 'basic-stripe',
    storageBucket: 'basic-stripe.appspot.com',
    iosBundleId: 'com.samwrotethecode.basicStripe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs8COsUTU0cJrw3vyYGp3_QeYlTm2-PaM',
    appId: '1:875225395768:ios:22442f9968c297fa7daccd',
    messagingSenderId: '875225395768',
    projectId: 'basic-stripe',
    storageBucket: 'basic-stripe.appspot.com',
    iosBundleId: 'com.samwrotethecode.basicStripe',
  );
}
